<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <defaultLandingTab>standard-Contact</defaultLandingTab>
    <tab>standard-Contact</tab>
    <tab>standard-Account</tab>
    <tab>standard-report</tab>
    <tab>standard-Dashboard</tab>
    <tab>standard-Chatter</tab>
    <tab>standard-File</tab>
    <tab>Property__c</tab>
    <tab>Lease__c</tab>
    <tab>Lease_Unit__c</tab>
    <tab>Lease_Charges__c</tab>
    <tab>Billing_Period__c</tab>
    <tab>POS_Transaction__c</tab>
    <tab>Invoice__c</tab>
    <tab>Invoice_Line_Item__c</tab>
    <tab>Cash_Receipt__c</tab>
    <tab>Rent_Roll__c</tab>
    <tab>Units__c</tab>
    <tab>Level__c</tab>
    <tab>Checklist_Master__c</tab>
    <tab>Rent_Schedules__c</tab>
    <tab>Checklist_Item__c</tab>
    <tab>Permission_Set__c</tab>
    <tab>Mobile_Module__c</tab>
    <tab>Generate_Rent_Roll</tab>
    <tab>Integration_AWS_Log__c</tab>
    <tab>AWS_Integration_Push_Pull</tab>
    <tab>Generate_Cash_Receipt</tab>
    <tab>Electric_Transaction__c</tab>
    <tab>Tasklist_Items__c</tab>
    <tab>Tasklist_Master__c</tab>
    <tab>Other_Invoices</tab>
    <tab>Lease_Plan__c</tab>
    <tab>HR_Workflow__c</tab>
    <tab>App_Setting__c</tab>
    <tab>Daily_Checklist__c</tab>
    <tab>Generate_Journal_Voucher</tab>
    <tab>Daily_Lease_Plan</tab>
    <tab>Generate_LOI</tab>
    <tab>Checklist_Master_Item__c</tab>
    <tab>Warranty__c</tab>
    <tab>Activity</tab>
    <tab>Daily_Checklist_Item__c</tab>
    <tab>Payment_Voucher__c</tab>
    <tab>DOA__c</tab>
    <tab>LOI_Unit_Template__c</tab>
    <tab>Stock__c</tab>
</CustomApplication>
