<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Small</formFactors>
    <formFactors>Medium</formFactors>
    <formFactors>Large</formFactors>
    <navType>Standard</navType>
    <tab>standard-home</tab>
    <tab>standard-Opportunity</tab>
    <tab>standard-Lead</tab>
    <tab>standard-Task</tab>
    <tab>standard-File</tab>
    <tab>standard-ContentNote</tab>
    <tab>standard-Account</tab>
    <tab>standard-Contact</tab>
    <tab>standard-Campaign</tab>
    <tab>standard-Dashboard</tab>
    <tab>standard-report</tab>
    <tab>standard-Feed</tab>
    <tab>standard-CollaborationGroup</tab>
    <tab>standard-Event</tab>
    <tab>standard-OtherUserProfile</tab>
    <tab>standard-Case</tab>
    <tab>standard-News</tab>
    <tab>standard-Forecasting3</tab>
    <tab>Mobile_Module__c</tab>
    <tab>Generate_Rent_Roll</tab>
    <tab>Integration_AWS_Log__c</tab>
    <tab>AWS_Integration_Push_Pull</tab>
    <tab>Generate_Cash_Receipt</tab>
    <tab>Electric_Transaction__c</tab>
    <tab>Tasklist_Items__c</tab>
    <tab>Tasklist_Master__c</tab>
    <tab>Other_Invoices</tab>
    <tab>Lease_Plan__c</tab>
    <tab>HR_Workflow__c</tab>
    <tab>standard-Quote</tab>
    <tab>App_Setting__c</tab>
    <tab>Daily_Checklist__c</tab>
    <tab>Generate_Journal_Voucher</tab>
    <tab>Daily_Lease_Plan</tab>
    <tab>Generate_LOI</tab>
    <tab>Checklist_Master_Item__c</tab>
    <tab>Activity</tab>
    <tab>Daily_Checklist_Item__c</tab>
    <tab>Payment_Voucher__c</tab>
    <tab>DOA__c</tab>
    <tab>LOI_Unit_Template__c</tab>
    <tab>Stock__c</tab>
    <uiType>Lightning</uiType>
</CustomApplication>
