<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Large</formFactors>
    <navType>Console</navType>
    <tab>standard-home</tab>
    <tab>standard-Lead</tab>
    <tab>standard-Account</tab>
    <tab>standard-Contact</tab>
    <tab>standard-Opportunity</tab>
    <tab>standard-Campaign</tab>
    <tab>standard-Task</tab>
    <tab>standard-Event</tab>
    <tab>standard-ContentNote</tab>
    <tab>standard-report</tab>
    <tab>standard-Dashboard</tab>
    <tab>standard-Feed</tab>
    <tab>standard-CollaborationGroup</tab>
    <tab>standard-File</tab>
    <tab>App_Setting__c</tab>
    <tab>Daily_Checklist__c</tab>
    <tab>Generate_Journal_Voucher</tab>
    <tab>Daily_Lease_Plan</tab>
    <tab>Generate_LOI</tab>
    <tab>Checklist_Master_Item__c</tab>
    <tab>Activity</tab>
    <tab>Daily_Checklist_Item__c</tab>
    <tab>Payment_Voucher__c</tab>
    <tab>DOA__c</tab>
    <tab>LOI_Unit_Template__c</tab>
    <tab>Stock__c</tab>
    <uiType>Lightning</uiType>
    <utilityBar>LightningSalesConsole_UtilityBar</utilityBar>
</CustomApplication>
