<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <defaultLandingTab>standard-home</defaultLandingTab>
    <detailPageRefreshMethod>none</detailPageRefreshMethod>
    <enableCustomizeMyTabs>false</enableCustomizeMyTabs>
    <enableKeyboardShortcuts>true</enableKeyboardShortcuts>
    <enableListViewHover>true</enableListViewHover>
    <enableListViewReskin>true</enableListViewReskin>
    <enableMultiMonitorComponents>true</enableMultiMonitorComponents>
    <enablePinTabs>true</enablePinTabs>
    <enableTabHover>false</enableTabHover>
    <enableTabLimits>false</enableTabLimits>
    <isServiceCloudConsole>true</isServiceCloudConsole>
    <keyboardShortcuts>
        <defaultShortcut>
            <action>FOCUS_CONSOLE</action>
            <active>true</active>
            <keyCommand>ESC</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_NAVIGATOR_TAB</action>
            <active>true</active>
            <keyCommand>V</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_DETAIL_VIEW</action>
            <active>true</active>
            <keyCommand>SHIFT+S</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_PRIMARY_TAB_PANEL</action>
            <active>true</active>
            <keyCommand>P</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_SUBTAB_PANEL</action>
            <active>true</active>
            <keyCommand>S</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_LIST_VIEW</action>
            <active>true</active>
            <keyCommand>N</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_FIRST_LIST_VIEW</action>
            <active>true</active>
            <keyCommand>SHIFT+F</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_SEARCH_INPUT</action>
            <active>true</active>
            <keyCommand>R</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>MOVE_LEFT</action>
            <active>true</active>
            <keyCommand>LEFT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>MOVE_RIGHT</action>
            <active>true</active>
            <keyCommand>RIGHT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>UP_ARROW</action>
            <active>true</active>
            <keyCommand>UP ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>DOWN_ARROW</action>
            <active>true</active>
            <keyCommand>DOWN ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>OPEN_TAB_SCROLLER_MENU</action>
            <active>true</active>
            <keyCommand>D</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>OPEN_TAB</action>
            <active>true</active>
            <keyCommand>T</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>CLOSE_TAB</action>
            <active>true</active>
            <keyCommand>C</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>REFRESH_TAB</action>
            <active>false</active>
            <keyCommand>SHIFT+R</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>ENTER</action>
            <active>true</active>
            <keyCommand>ENTER</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>EDIT</action>
            <active>true</active>
            <keyCommand>E</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>SAVE</action>
            <active>true</active>
            <keyCommand>CTRL+S</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>CONSOLE_LINK_DIALOG</action>
            <active>false</active>
            <keyCommand>U</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>HOTKEYS_PANEL</action>
            <active>false</active>
            <keyCommand>SHIFT+K</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_MACRO</action>
            <active>false</active>
            <keyCommand>M</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_FOOTER_PANEL</action>
            <active>false</active>
            <keyCommand>F</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_LIST_VIEW</action>
            <active>false</active>
            <keyCommand>SHIFT+N</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_LEFT_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+LEFT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_RIGHT_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+RIGHT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_TOP_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+UP ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_BOTTOM_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+DOWN ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_APP_LEVEL_COMPONENTS</action>
            <active>false</active>
            <keyCommand>Z</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>REOPEN_LAST_TAB</action>
            <active>false</active>
            <keyCommand>SHIFT+C</keyCommand>
        </defaultShortcut>
    </keyboardShortcuts>
    <listPlacement>
        <location>full</location>
    </listPlacement>
    <listRefreshMethod>none</listRefreshMethod>
    <saveUserSessions>true</saveUserSessions>
    <tab>standard-Account</tab>
    <tab>standard-Contact</tab>
    <tab>standard-Case</tab>
    <tab>standard-Opportunity</tab>
    <tab>standard-Lead</tab>
    <tab>Property__c</tab>
    <tab>Lease__c</tab>
    <tab>Lease_Unit__c</tab>
    <tab>Lease_Charges__c</tab>
    <tab>Billing_Period__c</tab>
    <tab>POS_Transaction__c</tab>
    <tab>Invoice__c</tab>
    <tab>Invoice_Line_Item__c</tab>
    <tab>Cash_Receipt__c</tab>
    <tab>Rent_Roll__c</tab>
    <tab>Units__c</tab>
    <tab>Level__c</tab>
    <tab>Checklist_Master__c</tab>
    <tab>Rent_Schedules__c</tab>
    <tab>Checklist_Item__c</tab>
    <tab>Permission_Set__c</tab>
    <tab>Mobile_Module__c</tab>
    <tab>Generate_Rent_Roll</tab>
    <tab>Integration_AWS_Log__c</tab>
    <tab>AWS_Integration_Push_Pull</tab>
    <tab>Generate_Cash_Receipt</tab>
    <tab>Electric_Transaction__c</tab>
    <tab>Tasklist_Items__c</tab>
    <tab>Tasklist_Master__c</tab>
    <tab>Other_Invoices</tab>
    <tab>Lease_Plan__c</tab>
    <tab>HR_Workflow__c</tab>
    <tab>App_Setting__c</tab>
    <tab>Daily_Checklist__c</tab>
    <tab>Generate_Journal_Voucher</tab>
    <tab>Daily_Lease_Plan</tab>
    <tab>Generate_LOI</tab>
    <tab>Checklist_Master_Item__c</tab>
    <tab>Activity</tab>
    <tab>Daily_Checklist_Item__c</tab>
    <tab>Payment_Voucher__c</tab>
    <tab>DOA__c</tab>
    <tab>LOI_Unit_Template__c</tab>
    <tab>Stock__c</tab>
    <workspaceMappings>
        <mapping>
            <tab>AWS_Integration_Push_Pull</tab>
        </mapping>
        <mapping>
            <tab>Activity</tab>
        </mapping>
        <mapping>
            <tab>App_Setting__c</tab>
        </mapping>
        <mapping>
            <tab>Billing_Period__c</tab>
        </mapping>
        <mapping>
            <tab>Cash_Receipt__c</tab>
        </mapping>
        <mapping>
            <tab>Checklist_Item__c</tab>
        </mapping>
        <mapping>
            <tab>Checklist_Master_Item__c</tab>
        </mapping>
        <mapping>
            <tab>Checklist_Master__c</tab>
        </mapping>
        <mapping>
            <tab>DOA__c</tab>
        </mapping>
        <mapping>
            <tab>Daily_Checklist_Item__c</tab>
        </mapping>
        <mapping>
            <tab>Daily_Checklist__c</tab>
        </mapping>
        <mapping>
            <tab>Daily_Lease_Plan</tab>
        </mapping>
        <mapping>
            <tab>Electric_Transaction__c</tab>
        </mapping>
        <mapping>
            <tab>Generate_Cash_Receipt</tab>
        </mapping>
        <mapping>
            <tab>Generate_Journal_Voucher</tab>
        </mapping>
        <mapping>
            <tab>Generate_LOI</tab>
        </mapping>
        <mapping>
            <tab>Generate_Rent_Roll</tab>
        </mapping>
        <mapping>
            <tab>HR_Workflow__c</tab>
        </mapping>
        <mapping>
            <tab>Integration_AWS_Log__c</tab>
        </mapping>
        <mapping>
            <tab>Invoice_Line_Item__c</tab>
        </mapping>
        <mapping>
            <tab>Invoice__c</tab>
        </mapping>
        <mapping>
            <tab>LOI_Unit_Template__c</tab>
        </mapping>
        <mapping>
            <tab>Lease_Charges__c</tab>
        </mapping>
        <mapping>
            <tab>Lease_Plan__c</tab>
        </mapping>
        <mapping>
            <tab>Lease_Unit__c</tab>
        </mapping>
        <mapping>
            <tab>Lease__c</tab>
        </mapping>
        <mapping>
            <tab>Level__c</tab>
        </mapping>
        <mapping>
            <tab>Mobile_Module__c</tab>
        </mapping>
        <mapping>
            <tab>Other_Invoices</tab>
        </mapping>
        <mapping>
            <tab>POS_Transaction__c</tab>
        </mapping>
        <mapping>
            <tab>Payment_Voucher__c</tab>
        </mapping>
        <mapping>
            <tab>Permission_Set__c</tab>
        </mapping>
        <mapping>
            <tab>Property__c</tab>
        </mapping>
        <mapping>
            <tab>Rent_Roll__c</tab>
        </mapping>
        <mapping>
            <tab>Rent_Schedules__c</tab>
        </mapping>
        <mapping>
            <tab>Stock__c</tab>
        </mapping>
        <mapping>
            <tab>Tasklist_Items__c</tab>
        </mapping>
        <mapping>
            <tab>Tasklist_Master__c</tab>
        </mapping>
        <mapping>
            <tab>Units__c</tab>
        </mapping>
        <mapping>
            <tab>standard-Account</tab>
        </mapping>
        <mapping>
            <fieldName>AccountId</fieldName>
            <tab>standard-Case</tab>
        </mapping>
        <mapping>
            <fieldName>AccountId</fieldName>
            <tab>standard-Contact</tab>
        </mapping>
        <mapping>
            <tab>standard-Lead</tab>
        </mapping>
        <mapping>
            <fieldName>AccountId</fieldName>
            <tab>standard-Opportunity</tab>
        </mapping>
    </workspaceMappings>
</CustomApplication>
